# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: PManager Develop Branch CI/CD

env:
  SECRET_KEY : ${{secrets.SECRET_KEY}}
  DB_URL : ${{secrets.DB_URL}}
  ID_AMM : ${{secrets.ID_AMM}}
  ID_RIV : ${{secrets.ID_RIV}}

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pmanagerbackend-develop"
          heroku_email: "andrea.zanette@studenti.unitn.it"
          branch: "develop"